services:
    cmdb-web:
        build:
            dockerfile: WebDockerfile
        depends_on:
            - cmdb-api
        ports:
            - 44313:8080
            - 44314:8081
        networks:
            - my_net

    cmdb-api:
        build: 
            dockerfile: ApiDockerfile
        ports:
            - 7055:8080
            - 7054:8081
        networks:
            - my_net
        
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:7055/swagger"]
            interval: 2s
            timeout: 5s
            retries: 3

networks:
    my_net:
        driver: bridge